//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id { get; set; }
        public string pNombre { get; set; }
        public string sNombre { get; set; }
        public string apPaterno { get; set; }
        public string apMaterno { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public System.DateTime creado { get; set; }
        public bool estado { get; set; }
        public string direccion { get; set; }
        public string comuna { get; set; }
        public string region { get; set; }
        public int IdRol { get; set; }
    
        public virtual rol rol { get; set; }
    }
}
